# Generated by Django 3.0.4 on 2020-04-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carslist_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='fuel_count',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
