# Generated by Django 3.0.4 on 2020-05-13 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmanager', '0002_auto_20200405_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_article', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('name_article', models.CharField(max_length=200)),
                ('art_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('text_article', models.TextField(blank=True)),
                ('visible_article', models.BooleanField(default=True)),
                ('carmanager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carmanager.CarManager')),
            ],
        ),
    ]
